# Generated by Django 3.1.1 on 2020-09-26 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200926_1921'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
