# Generated by Django 3.1.1 on 2020-09-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200926_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favoutes',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
